//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuuTruVanThu_Project.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VanThuDBEntities : DbContext
    {
        public VanThuDBEntities()
            : base("name=VanThuDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonVi_Nam> DonVi_Nam { get; set; }
        public virtual DbSet<DonVis> DonVis { get; set; }
        public virtual DbSet<Nams> Nams { get; set; }
        public virtual DbSet<VanBanDens> VanBanDens { get; set; }
        public virtual DbSet<VanBanDis> VanBanDis { get; set; }
    }
}
