//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuuTruVanThu_Project.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VanBanDis
    {
        public string SoDi { get; set; }
        public string SoKyHieu { get; set; }
        public string TrichYeuNoiDung { get; set; }
        public string LoaiVanBan { get; set; }
        public string DonViBanHanh { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string NoiNhan { get; set; }
        public Nullable<System.DateTime> NgayXuLy { get; set; }
        public string TepTuLieu { get; set; }
        public Nullable<int> MaDonVi { get; set; }
    
        public virtual DonVis DonVis { get; set; }
    }
}
